export interface State {
  code: string
  name: string
  cities: string[]
}

export const brazilianStates: State[] = [
  {
    code: "AC",
    name: "Acre",
    cities: [
      "Rio Branco",
      "Cruzeiro do Sul",
      "Sena Madureira",
      "Tarauacá",
      "Feijó",
      "Brasileia",
      "Plácido de Castro",
      "Xapuri",
      "Epitaciolândia",
      "Mâncio Lima",
      "Senador Guiomard",
      "Capixaba",
      "Rodrigues Alves",
      "Acrelândia",
      "Assis Brasil",
      "Bujari",
      "Jordão",
      "Marechal Thaumaturgo",
      "Porto Walter",
      "Santa Rosa do Purus",
    ],
  },
  {
    code: "AL",
    name: "Alagoas",
    cities: [
      "Maceió",
      "Arapiraca",
      "Rio Largo",
      "Palmeira dos Índios",
      "União dos Palmares",
      "Penedo",
      "Coruripe",
      "São Miguel dos Campos",
      "Santana do Ipanema",
      "Delmiro Gouveia",
      "Marechal Deodoro",
      "Pilar",
      "Girau do Ponciano",
      "Campo Alegre",
      "Murici",
      "Porto Calvo",
      "Viçosa",
      "São Luís do Quitunde",
      "Matriz de Camaragibe",
      "Quebrangulo",
    ],
  },
  {
    code: "AP",
    name: "Amapá",
    cities: [
      "Macapá",
      "Santana",
      "Laranjal do Jari",
      "Oiapoque",
      "Porto Grande",
      "Mazagão",
      "Pedra Branca do Amapari",
      "Vitória do Jari",
      "Tartarugalzinho",
      "Amapá",
      "Ferreira Gomes",
      "Pracuúba",
      "Calçoene",
      "Cutias",
      "Itaubal",
      "Serra do Navio",
    ],
  },
  {
    code: "AM",
    name: "Amazonas",
    cities: [
      "Manaus",
      "Parintins",
      "Itacoatiara",
      "Manacapuru",
      "Coari",
      "Tefé",
      "Tabatinga",
      "Maués",
      "São Paulo de Olivença",
      "Humaitá",
      "Lábrea",
      "Manicoré",
      "Autazes",
      "Carauari",
      "Eirunepé",
      "Iranduba",
      "Presidente Figueiredo",
      "Benjamin Constant",
      "Fonte Boa",
      "Novo Airão",
      "Careiro",
      "Silves",
      "Urucará",
      "Nhamundá",
      "Barreirinha",
    ],
  },
  {
    code: "BA",
    name: "Bahia",
    cities: [
      "Salvador",
      "Feira de Santana",
      "Vitória da Conquista",
      "Camaçari",
      "Juazeiro",
      "Petrolina",
      "Lauro de Freitas",
      "Itabuna",
      "Jequié",
      "Teixeira de Freitas",
      "Alagoinhas",
      "Barreiras",
      "Porto Seguro",
      "Simões Filho",
      "Paulo Afonso",
      "Eunápolis",
      "Candeias",
      "Guanambi",
      "Jacobina",
      "Serrinha",
      "Senhor do Bonfim",
      "Dias d'Ávila",
      "Luís Eduardo Magalhães",
      "Ilhéus",
      "Valença",
      "Cruz das Almas",
    ],
  },
  {
    code: "CE",
    name: "Ceará",
    cities: [
      "Fortaleza",
      "Caucaia",
      "Juazeiro do Norte",
      "Maracanaú",
      "Sobral",
      "Crato",
      "Itapipoca",
      "Maranguape",
      "Iguatu",
      "Quixadá",
      "Canindé",
      "Aquiraz",
      "Pacatuba",
      "Crateús",
      "Russas",
      "Aracati",
      "Cascavel",
      "Pacajus",
      "Icó",
      "Horizonte",
      "Camocim",
      "Morada Nova",
      "Acaraú",
      "Viçosa do Ceará",
      "Barbalha",
      "Limoeiro do Norte",
    ],
  },
  {
    code: "DF",
    name: "Distrito Federal",
    cities: [
      "Brasília",
      "Gama",
      "Taguatinga",
      "Ceilândia",
      "Sobradinho",
      "Planaltina",
      "São Sebastião",
      "Recanto das Emas",
      "Santa Maria",
      "Samambaia",
      "Riacho Fundo",
      "Núcleo Bandeirante",
      "Brazlândia",
      "Guará",
      "Cruzeiro",
      "Lago Sul",
      "Lago Norte",
      "Candangolândia",
      "Águas Claras",
      "Vicente Pires",
      "Varjão",
      "Park Way",
      "SCIA",
      "Sobradinho II",
      "Jardim Botânico",
      "Itapoã",
      "SIA",
      "Fercal",
    ],
  },
  {
    code: "ES",
    name: "Espírito Santo",
    cities: [
      "Vitória",
      "Vila Velha",
      "Cariacica",
      "Serra",
      "Cachoeiro de Itapemirim",
      "Linhares",
      "São Mateus",
      "Colatina",
      "Guarapari",
      "Aracruz",
      "Viana",
      "Nova Venécia",
      "Barra de São Francisco",
      "Santa Teresa",
      "Castelo",
      "Marataízes",
      "Itapemirim",
      "Domingos Martins",
      "Afonso Cláudio",
      "Alegre",
      "Baixo Guandu",
      "Conceição da Barra",
      "Fundão",
      "Governador Lindenberg",
      "Iúna",
    ],
  },
  {
    code: "GO",
    name: "Goiás",
    cities: [
      "Goiânia",
      "Aparecida de Goiânia",
      "Anápolis",
      "Rio Verde",
      "Luziânia",
      "Águas Lindas de Goiás",
      "Valparaíso de Goiás",
      "Trindade",
      "Formosa",
      "Novo Gama",
      "Itumbiara",
      "Senador Canedo",
      "Catalão",
      "Jataí",
      "Planaltina",
      "Caldas Novas",
      "Santo Antônio do Descoberto",
      "Goianésia",
      "Cidade Ocidental",
      "Mineiros",
      "Cristalina",
      "Inhumas",
      "Uruaçu",
      "Porangatu",
      "Quirinópolis",
    ],
  },
  {
    code: "MA",
    name: "Maranhão",
    cities: [
      "São Luís",
      "Imperatriz",
      "São José de Ribamar",
      "Timon",
      "Caxias",
      "Codó",
      "Paço do Lumiar",
      "Açailândia",
      "Bacabal",
      "Balsas",
      "Barra do Corda",
      "Chapadinha",
      "Santa Inês",
      "Pinheiro",
      "Pedreiras",
      "Presidente Dutra",
      "Tutóia",
      "Coroatá",
      "Grajaú",
      "Itapecuru Mirim",
      "Viana",
      "Rosário",
      "Zé Doca",
      "Carolina",
      "Araioses",
    ],
  },
  {
    code: "MT",
    name: "Mato Grosso",
    cities: [
      "Cuiabá",
      "Várzea Grande",
      "Rondonópolis",
      "Sinop",
      "Tangará da Serra",
      "Cáceres",
      "Sorriso",
      "Lucas do Rio Verde",
      "Barra do Garças",
      "Primavera do Leste",
      "Alta Floresta",
      "Diamantino",
      "Juína",
      "Nova Mutum",
      "Colíder",
      "Pontes e Lacerda",
      "Mirassol d'Oeste",
      "Guarantã do Norte",
      "Peixoto de Azevedo",
      "Campo Verde",
      "Água Boa",
      "Comodoro",
      "Jaciara",
      "São José do Rio Claro",
      "Matupá",
    ],
  },
  {
    code: "MS",
    name: "Mato Grosso do Sul",
    cities: [
      "Campo Grande",
      "Dourados",
      "Três Lagoas",
      "Corumbá",
      "Ponta Porã",
      "Naviraí",
      "Nova Andradina",
      "Sidrolândia",
      "Maracaju",
      "São Gabriel do Oeste",
      "Coxim",
      "Aquidauana",
      "Paranaíba",
      "Amambai",
      "Ribas do Rio Pardo",
      "Miranda",
      "Caarapó",
      "Bonito",
      "Anastácio",
      "Jardim",
      "Chapadão do Sul",
      "Ivinhema",
      "Cassilândia",
      "Nova Alvorada do Sul",
      "Bataguassu",
    ],
  },
  {
    code: "MG",
    name: "Minas Gerais",
    cities: [
      "Belo Horizonte",
      "Uberlândia",
      "Contagem",
      "Juiz de Fora",
      "Betim",
      "Montes Claros",
      "Ribeirão das Neves",
      "Uberaba",
      "Governador Valadares",
      "Ipatinga",
      "Sete Lagoas",
      "Divinópolis",
      "Santa Luzia",
      "Ibirité",
      "Poços de Caldas",
      "Patos de Minas",
      "Pouso Alegre",
      "Teófilo Otoni",
      "Barbacena",
      "Sabará",
      "Varginha",
      "Conselheiro Lafaiete",
      "Vespasiano",
      "Itabira",
      "Araguari",
      "Passos",
      "Ubá",
      "Coronel Fabriciano",
      "Muriaé",
      "Ituiutaba",
      "Lavras",
      "Nova Lima",
      "Itajubá",
      "Pará de Minas",
      "Paracatu",
      "Caratinga",
    ],
  },
  {
    code: "PA",
    name: "Pará",
    cities: [
      "Belém",
      "Ananindeua",
      "Santarém",
      "Marabá",
      "Parauapebas",
      "Castanhal",
      "Abaetetuba",
      "Cametá",
      "Marituba",
      "Tucuruí",
      "Bragança",
      "Paragominas",
      "Redenção",
      "Altamira",
      "Itaituba",
      "Capanema",
      "Tailândia",
      "Barcarena",
      "Oriximiná",
      "Breves",
      "Salinópolis",
      "Tomé-Açu",
      "Vigia",
      "São Félix do Xingu",
      "Conceição do Araguaia",
      "Moju",
      "Benevides",
    ],
  },
  {
    code: "PB",
    name: "Paraíba",
    cities: [
      "João Pessoa",
      "Campina Grande",
      "Santa Rita",
      "Patos",
      "Bayeux",
      "Sousa",
      "Cajazeiras",
      "Cabedelo",
      "Guarabira",
      "Mamanguape",
      "Sapé",
      "Esperança",
      "Pombal",
      "Monteiro",
      "Areia",
      "Picuí",
      "Itabaiana",
      "Conde",
      "Princesa Isabel",
      "Bananeiras",
      "Caaporã",
      "São Bento",
      "Queimadas",
      "Solânea",
      "Alagoa Grande",
    ],
  },
  {
    code: "PR",
    name: "Paraná",
    cities: [
      "Curitiba",
      "Londrina",
      "Maringá",
      "Ponta Grossa",
      "Cascavel",
      "São José dos Pinhais",
      "Foz do Iguaçu",
      "Colombo",
      "Guarapuava",
      "Paranaguá",
      "Araucária",
      "Toledo",
      "Apucarana",
      "Pinhais",
      "Campo Largo",
      "Arapongas",
      "Almirante Tamandaré",
      "Umuarama",
      "Piraquara",
      "Cambé",
      "Campo Mourão",
      "Fazenda Rio Grande",
      "Sarandi",
      "Fazenda Rancharia",
      "Paranavaí",
      "Francisco Beltrão",
      "Pato Branco",
      "Cianorte",
      "Telêmaco Borba",
      "Castro",
    ],
  },
  {
    code: "PE",
    name: "Pernambuco",
    cities: [
      "Recife",
      "Jaboatão dos Guararapes",
      "Olinda",
      "Bandeira",
      "Caruaru",
      "Petrolina",
      "Paulista",
      "Cabo de Santo Agostinho",
      "Camaragibe",
      "Garanhuns",
      "Vitória de Santo Antão",
      "Igarassu",
      "São Lourenço da Mata",
      "Santa Cruz do Capibaribe",
      "Abreu e Lima",
      "Ipojuca",
      "Serra Talhada",
      "Araripina",
      "Gravatá",
      "Carpina",
      "Goiana",
      "Belo Jardim",
      "Arcoverde",
      "Ouricuri",
      "Escada",
      "Pesqueira",
      "Surubim",
      "Palmares",
      "Bezerros",
    ],
  },
  {
    code: "PI",
    name: "Piauí",
    cities: [
      "Teresina",
      "Parnaíba",
      "Picos",
      "Piripiri",
      "Floriano",
      "Campo Maior",
      "Barras",
      "União",
      "Altos",
      "Pedro II",
      "Valença do Piauí",
      "Esperantina",
      "São Raimundo Nonato",
      "Corrente",
      "Oeiras",
      "Amarante",
      "Luís Correia",
      "Bom Jesus",
      "Água Branca",
      "Regeneração",
      "Cocal",
      "Simplício Mendes",
      "Jaicós",
      "São João do Piauí",
      "Luzilândia",
    ],
  },
  {
    code: "RJ",
    name: "Rio de Janeiro",
    cities: [
      "Rio de Janeiro",
      "São Gonçalo",
      "Duque de Caxias",
      "Nova Iguaçu",
      "Niterói",
      "Belford Roxo",
      "Campos dos Goytacazes",
      "São João de Meriti",
      "Petrópolis",
      "Volta Redonda",
      "Magé",
      "Macaé",
      "Itaboraí",
      "Cabo Frio",
      "Angra dos Reis",
      "Nova Friburgo",
      "Barra Mansa",
      "Teresópolis",
      "Mesquita",
      "Nilópolis",
      "Maricá",
      "Queimados",
      "Rio das Ostras",
      "Resende",
      "Araruama",
      "Tanguá",
      "Saquarema",
      "Paracambi",
      "Itaguaí",
      "Seropédica",
    ],
  },
  {
    code: "RN",
    name: "Rio Grande do Norte",
    cities: [
      "Natal",
      "Mossoró",
      "Parnamirim",
      "São Gonçalo do Amarante",
      "Macaíba",
      "Ceará-Mirim",
      "Caicó",
      "Assu",
      "Currais Novos",
      "São José de Mipibu",
      "Santa Cruz",
      "João Câmara",
      "Canguaretama",
      "Nova Cruz",
      "Touros",
      "Extremoz",
      "São Paulo do Potengi",
      "Apodi",
      "Baraúna",
      "Areia Branca",
      "Pau dos Ferros",
      "São Bento do Norte",
      "Nísia Floresta",
      "Monte Alegre",
      "Goianinha",
    ],
  },
  {
    code: "RS",
    name: "Rio Grande do Sul",
    cities: [
      "Porto Alegre",
      "Caxias do Sul",
      "Pelotas",
      "Canoas",
      "Santa Maria",
      "Gravataí",
      "Viamão",
      "Novo Hamburgo",
      "São Leopoldo",
      "Rio Grande",
      "Alvorada",
      "Passo Fundo",
      "Sapucaia do Sul",
      "Uruguaiana",
      "Santa Cruz do Sul",
      "Cachoeirinha",
      "Bagé",
      "Bento Gonçalves",
      "Erechim",
      "Guaíba",
      "Cachoeira do Sul",
      "Santana do Livramento",
      "Ijuí",
      "Sapiranga",
      "Santo Ângelo",
      "Alegrete",
      "Lajeado",
      "Marau",
      "Santa Rosa",
      "Venâncio Aires",
    ],
  },
  {
    code: "RO",
    name: "Rondônia",
    cities: [
      "Porto Velho",
      "Ji-Paraná",
      "Ariquemes",
      "Vilhena",
      "Cacoal",
      "Rolim de Moura",
      "Guajará-Mirim",
      "Jaru",
      "Ouro Preto do Oeste",
      "Machadinho d'Oeste",
      "Presidente Médici",
      "Espigão d'Oeste",
      "Colorado do Oeste",
      "Cerejeiras",
      "Alta Floresta d'Oeste",
      "Pimenta Bueno",
      "Buritis",
      "Cujubim",
      "Nova Brasilândia d'Oeste",
      "Chupinguaia",
      "Corumbiara",
      "Costa Marques",
      "Ministro Andreazza",
      "Mirante da Serra",
      "Monte Negro",
    ],
  },
  {
    code: "RR",
    name: "Roraima",
    cities: [
      "Boa Vista",
      "Rorainópolis",
      "Caracaraí",
      "Alto Alegre",
      "Mucajaí",
      "Cantá",
      "Bonfim",
      "Normandia",
      "São Luiz",
      "São João da Baliza",
      "Caroebe",
      "Iracema",
      "Amajari",
      "Pacaraima",
      "Uiramutã",
    ],
  },
  {
    code: "SC",
    name: "Santa Catarina",
    cities: [
      "Joinville",
      "Florianópolis",
      "Blumenau",
      "São José",
      "Criciúma",
      "Chapecó",
      "Itajaí",
      "Lages",
      "Jaraguá do Sul",
      "Palhoça",
      "Balneário Camboriú",
      "Brusque",
      "Tubarão",
      "São Bento do Sul",
      "Caçador",
      "Camboriú",
      "Navegantes",
      "Concórdia",
      "Rio do Sul",
      "Araranguá",
      "Gaspar",
      "Biguaçu",
      "Indaial",
      "Itapema",
      "Mafra",
      "Canoinhas",
      "Içara",
      "Videira",
      "Timbó",
      "Araquari",
    ],
  },
  {
    code: "SP",
    name: "São Paulo",
    cities: [
      "São Paulo",
      "Guarulhos",
      "Campinas",
      "São Bernardo do Campo",
      "Santo André",
      "Osasco",
      "Ribeirão Preto",
      "Sorocaba",
      "Mauá",
      "São José dos Campos",
      "Mogi das Cruzes",
      "Diadema",
      "Jundiaí",
      "Carapicuíba",
      "Piracicaba",
      "Bauru",
      "São Vicente",
      "Franca",
      "Itaquaquecetuba",
      "Guarujá",
      "Taubaté",
      "Praia Grande",
      "Limeira",
      "Suzano",
      "Taboão da Serra",
      "Sumaré",
      "Barueri",
      "Embu das Artes",
      "São Carlos",
      "Marília",
      "Indaiatuba",
      "Cotia",
      "Americana",
      "Jacareí",
      "Araraquara",
      "Santos",
      "Hortolândia",
      "Presidente Prudente",
      "São Caetano do Sul",
    ],
  },
  {
    code: "SE",
    name: "Sergipe",
    cities: [
      "Aracaju",
      "Nossa Senhora do Socorro",
      "Lagarto",
      "Itabaiana",
      "São Cristóvão",
      "Estância",
      "Tobias Barreto",
      "Simão Dias",
      "Propriá",
      "Barra dos Coqueiros",
      "Glória",
      "Itabaianinha",
      "Ribeirópolis",
      "Neópolis",
      "Porto da Folha",
      "Canindé de São Francisco",
      "Aquidabã",
      "Carmópolis",
      "Rosário do Catete",
      "Maruim",
      "Campo do Brito",
      "Arauá",
      "Frei Paulo",
      "Riachuelo",
      "Capela",
    ],
  },
  {
    code: "TO",
    name: "Tocantins",
    cities: [
      "Palmas",
      "Araguaína",
      "Gurupi",
      "Porto Nacional",
      "Paraíso do Tocantins",
      "Colinas do Tocantins",
      "Guaraí",
      "Formoso do Araguaia",
      "Dianópolis",
      "Tocantinópolis",
      "Araguatins",
      "Pedro Afonso",
      "Miracema do Tocantins",
      "Xambioá",
      "Taguatinga",
      "Augustinópolis",
      "Colméia",
      "Wanderlândia",
      "Babaçulândia",
      "Alvorada",
      "Arraias",
      "Filadélfia",
      "Goiatins",
      "Natividade",
      "Peixe",
    ],
  },
]

export const getStateByCode = (code: string): State | undefined => {
  return brazilianStates.find((state) => state.code === code)
}

export const getCitiesByState = (stateCode: string): string[] => {
  const state = getStateByCode(stateCode)
  return state ? state.cities : []
}
